ompd_bp_parallel_begin() needs to be called for all parallel constructs and not only for serialized regi
OpenMPToolsInterface/llvm-project pull request #3
Opened 2020-04-21 15:46 UTC by jinisusan

Currently, the ompd_bp_parallel_start() routine gets called only in the case of serialized parallel regions. With this PR, I have made modifications so that this gets called at the beginning of the execution of every parallel construct. I had a couple of doubts which I raised in the group also.

•	I am assuming that ompd_bp_parallel_start() should get invoked only for the parallel constructs, and not for teams constructs (unlike the OMPT parallel begin events).
•	The spec mentions: At the point that the implementation reaches ompd_bp_parallel_begin, the binding for ompd_get_curr_parallel_handle is the parallel region that is beginning and the binding for ompd_get_curr_task_handle is the task that encountered the parallel construct. 
          This is not the case with the current sources or even with this PR. Currently, when the implementation reaches ompd_bp_parallel_begin(), the binding for the ompd_get_curr_parallel_handle() is the region enclosing the parallel region that is beginning. I feel that what the spec mentions wrt the parallel-begin event in the case of OMPT is more appropriate – where the following is mentioned there. 

Between a parallel-begin event and an implicit-task-begin event, a call to ompt_get_parallel_info(0,...) may return information about the outer parallel team,  the new parallel team or an inconsistent state.

2020-04-28 04:35 UTC, jinisusan commented
Gentle reminder ! Requesting for reviews

2020-04-28 11:56 UTC, jdelsign commented
@jinisusan Sorry, I have no idea if this is correct or not. I'm not at all familiar with the OMP runtime.

2020-04-28 13:21 UTC, jinisusan commented
Thank you for letting me know, @jdelsign. @jprotze, will you be able to take a look ? 


Thanks.

2020-06-02 11:24 UTC, jinisusan commented
@jprotze, Gentle reminder !

2020-06-08 16:49 UTC, jprotze requested changes
Sorry, that it took so long, but I knew it would be complicated.

The spec says:

> At the point that the implementation reaches
> ompd_bp_parallel_begin, the binding for ompd_get_curr_parallel_handle is the
> parallel region that is beginning and the binding for ompd_get_curr_task_handle is the
> task that encountered the parallel construct.

At the point, where you moved ompd_bp_parallel_begin, still the old team is seen as the binding team.

The pointer for the current (active) team is updated in `__kmp_allocate_team`. So for active parallel regions, I think the breakpoint should be called arround `propagateFPControl` in line 2073.

For inactive teams, the tool specific information is stored and managed with the `__ompt_lw_taskteam_link` function. Once this function is called, we will see the new team as the binding team. Unfortunately, __ompt_lw_taskteam_link at the same time makes the new implicit task active.

I think, we should move the breakpoint for inactive teams inside of `__ompt_lw_taskteam_link`, and add a flag to the `ompt_team_info_t` struct, which signals that the new task should be skipped in `ompd_get_curr_task_handle`. This could go to the end of `__ompt_lw_taskteam_link`:

```C
if ( ompd_state & OMPD_ENABLE_BP ) {
  OMPT_CUR_TEAM_INFO(thr)->skip_implicit_task=1;
  ompd_bp_parallel_begin ();
  OMPT_CUR_TEAM_INFO(thr)->skip_implicit_task=0;
}
```

2020-06-15 10:26 UTC, jinisusan commented
Thank you very much, @jprotze, for the review ! Instead of the skip_implicit_task flag, I made changes to invoke ompd_bp_parallel_begin() for the inactive parallel regions in __ompt_lw_taskteam_link() after the bindng to the new team but before binding to the new task. Does this look ok ? Another doubt that I have is that currently ompd_bp_parallel_begin() gets invoked for teams constructs also -- is that expected behavior ?

2020-06-15 15:44 UTC, jprotze commented
The changes look good to me. I did not test, though.

For OMPD we did not consider the teams construct specially. I think, for the breakpoint it's not so important to make a distinction between league and team.

2020-06-15 15:44 UTC, merged