Implemented API ompd_get_omp_version_string()
OpenMPToolsInterface/llvm-project pull request #40
Opened 2021-01-18 08:55 UTC by vigbalu

Current one is a skeletal implementation and returns "". Implemented to return omp version string.

2021-01-19 09:51 UTC, jinisusan approved these changes

2021-01-20 09:26 UTC, jprotze requested changes
From the OpenMP spec:
> After returning from the call, the tool owns the
> string. The OMPD library must use the memory allocation callback that the tool provides to
> allocate the string storage. The tool is responsible for releasing the memory.

Since alloc and copy a string seems to be a common operation (@jinisusan  https://github.com/OpenMPToolsInterface/llvm-project/pull/37) I suggest to add a helper function, which accepts a `const char*`, checks the length, allocates the buffer and copies the string.
In any case, this function should only be called after handling any error that might occur in the function.

2021-02-02 09:00 UTC, vigbalu commented
I can have helper function as below, but seems it can be used only in couple of places. Not possible in (#37 ) because there is a concatenation operation after string is copied.

Please let me know if you want me to proceed with this.

ompd_rc_t alloc_and_copy_str (const char* str, char** new_str) {
  ompd_rc_t ret;
  int str_length = strlen(str) + 1/*for '\0'*/;
  ret = callbacks->alloc_memory(str_length, (void **) new_str);
  if (ret != ompd_rc_ok) {
    return ret;
  }

  strcpy (*new_str, str);
  return ompd_rc_ok;
}

2021-02-03 15:21 UTC, jprotze commented
I'm fine either way, we just cannot use static memory here.

2024-01-24 01:53 UTC, closed without merging